GstCabinetClient/Models/Disponibilite.cs
namespace GstCabinetClient.Models
{
    public class Disponibilite
    {
     
        public int Id { get; set; }
        public DateTime DateRendezvous { get; set; }
        public TimeSpan? Horraire { get; set; }
        public Medcin? Medcin { get; set; }
        public int? MedcinID { get; set; }
    }
}

GstCabinetClient/Models/ErrorViewModel.cs
namespace GstCabinetClient.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GstCabinetClient/Models/Medcin.cs
using System.ComponentModel.DataAnnotations;

namespace GstCabinetClient.Models
{
    public class Medcin
    {
        [Key]
        public int Id { get; set; }
        public string ?Nom { get; set; }
        public string ?Prenom { get; set; }
        public string? Adresse { get; set; }
        public string? Telephone { get; set; }
        [DataType(DataType.EmailAddress)]
        public string ?Email { get; set; }
        [DataType(DataType.Password)]
        public string? Password { get; set; }
        public string? Ville { get; set;}
        public string? Specialité { get; set; }
        public List<RendezVous>?rendezVous { get; set; }
        public List<Disponibilite>?disponibilites { get; set; }  



    }
}

GstCabinetClient/Models/Patient.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GstCabinetClient.Models
{
    public class Patient
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string? Nom { get; set; }
        public string? Prenom { get; set; }
        public string? Adresse { get; set; }
        public string? Telephone { get; set; }
        public string? Email { get; set; }
        public string? Password { get; set; }
        public string ?Sexe { get; set; }
        public DateTime ?DateNaissance { get; set; }
        public List<RendezVous>? rendezVous { get; set; }


    }
}

GstCabinetClient/Models/RendezVous.cs
using GstCabinetClient.Models;
using System.ComponentModel.DataAnnotations;

namespace GstCabinetClient.Models
{
    public class RendezVous
    {
        [Key]
        public int Num { get; set; }
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public TimeSpan ?Horraire { get; set; }
     //   public string? Etat { get; set; }
        public Medcin ?Medcin { get; set; }
        public int ?MedcinID { get; set; }
        public Patient? Patient { get; set; }
        public int ?PatientID { get; set; }


    }
}

GstCabinetClient/Controllers/AuthentificationController.cs
using GstCabinetClient.Models;
using Microsoft.AspNetCore.Mvc;

namespace GstCabinetClient.Controllers
{
    public class AuthentificationController : Controller
    {
        public ApplicationContext db;
        public AuthentificationController(ApplicationContext db)
        {
            this.db = db;
        }
        public IActionResult Connect()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Connect(Patient patient)
        {
            var pt = db.Patients.FirstOrDefault(m => m.Email.Equals(patient.Email) && m.Password.Equals(patient.Password));
            if (pt != null)
            {
                HttpContext.Session.SetInt32("Id", pt.Id);
                HttpContext.Session.SetString("fullname", pt.Nom + " " + pt.Prenom);
                return RedirectToAction("List", "RendezVous");
            }
            return View(patient);
        }
    }
}

GstCabinetClient/Controllers/HomeController.cs
using GstCabinetClient.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Numerics;

namespace GstCabinetClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public ApplicationContext db;
        public HomeController(ApplicationContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            var disponibilites = db.Disponibilites.ToList();
            var doctors = db.Medcins.ToList();
            ViewBag.doctors = doctors;
            ViewBag.RendezVous = db.RendezVous.ToList();
            return View(disponibilites);
        }
        public IActionResult GetPartial(int medcinid=0,int num=1)
        {
            //num ==numero de semaine
            var disponibilites = db.Disponibilites.Where(d => d.MedcinID == medcinid).ToList();
            var doctors = db.Medcins.ToList();
            ViewBag.doctors = doctors;
            ViewBag.RendezVous = db.RendezVous.ToList();

            ViewBag.num = num;
            ViewBag.medcinid = medcinid;

            return PartialView("_PartialCalendar", disponibilites);
        }
    }
}

GstCabinetClient/Controllers/MedcinController.cs
using Microsoft.AspNetCore.Mvc;

namespace GstCabinetClient.Controllers
{
    public class MedcinController : Controller
    {



        public IActionResult Index()
        {
            return View();
        }
    }
}

GstCabinetClient/Controllers/PatientController.cs
using GstCabinetClient.Models;
using Microsoft.AspNetCore.Mvc;

namespace GstCabinetClient.Controllers
{
    public class PatientController : Controller
    {
        public ApplicationContext db;
        public PatientController(ApplicationContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Add(Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(patient);
        }

    }
}

GstCabinetClient/Controllers/RendezVousController.cs
using GstCabinetClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GstCabinetClient.Controllers
{
    public class RendezVousController : Controller
    {
        public ApplicationContext db;
        public RendezVousController(ApplicationContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Add(int Id, int uId)
        {
            HttpContext.Session.SetInt32("Idispo", Id);
            HttpContext.Session.SetInt32("Idmed", uId);
            return View();
        }
        [HttpPost]
        public IActionResult Add(Patient patient)
        {
            //si iil est pas inscrit
            int? idpati = HttpContext.Session.GetInt32("Id");
            if (idpati==null)
            {
                patient.Id = 0;
                db.Patients.Add(patient);
                db.SaveChanges();
                idpati = patient.Id;
            }
                int? idispo = HttpContext.Session.GetInt32("Idispo");
                int? medid = HttpContext.Session.GetInt32("Idmed");
                var dispo = db.Disponibilites.FirstOrDefault(d => d.Id == idispo);
                var nouveauRendezVous = new RendezVous
                {
                    Date = dispo.DateRendezvous,
                    Horraire = dispo.Horraire,
                    PatientID = idpati,
                    MedcinID = medid,


                };

                db.RendezVous.Add(nouveauRendezVous);
                db.SaveChanges();
                HttpContext.Session.Remove("Idispo");
                HttpContext.Session.Remove("Idmed");
                return RedirectToAction("Index", "Home");
            
        }
        public IActionResult List()
        {
            int? idpati = HttpContext.Session.GetInt32("Id");
            List<RendezVous> lists = new List<RendezVous>();
                if (idpati.HasValue)
                {
                     lists = db.RendezVous.Include(t => t.Medcin).ToList();
                }

            return View(lists);
        }
          
        }
    }

GstCabinetClient/Views/Authentification/Connect.cshtml
@model Patient

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <div class="content">
        <div class="container">
            <div class="row justify-content-center">
                <!-- <div class="col-md-6 order-md-2">
                  <img src="images/undraw_file_sync_ot38.svg" alt="Image" class="img-fluid">
                </div> -->
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="form-block">
                                <div class="mb-4">
                                    <h3>Se connecter</h3>
                                </div>
                                <form action="@Url.Action("Connect","Authentification")" method="post">
                                    <div class="form-group first">
                                        <label for="username">Email</label>
                                        <input type="email" class="form-control" asp-for="Email">
                                        <span asp-validation-for="Email"/>

                                    </div>
                                    <div class="form-group last mb-4">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control" asp-for="Password">
                                        <span asp-validation-for="Password" />

                                    </div>

                                    

                                    <input type="submit" value="Se connecter" class="btn btn-pill text-white btn-block btn-success">

                                  

                                    <div class="social-login text-center">
                                        <a href="#" class="facebook">
                                            <span class="icon-facebook mr-3"></span>
                                        </a>
                                        <a href="#" class="twitter">
                                            <span class="icon-twitter mr-3"></span>
                                        </a>
                                        <a href="#" class="google">
                                            <span class="icon-google mr-3"></span>
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>


    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

GstCabinetClient/Views/Home/Index.cshtml
@model List<Disponibilite>
@{
    var medcins = (List<Medcin>)ViewBag.doctors;
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.js" integrity="sha512-8Z5++K1rB3U+USaLKG6oO8uWWBhdYsM3hmdirnOEWp8h2B1aOikj5zBzlXs8QOrvY9OxEnD2QDkbSKKpfqcIWw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    let pos = [];
    function getcalendar(i, weeknum, idmedcin) {
        pos[i] = parseInt(pos[i]) + parseInt(weeknum);

        if (pos[i] == 1)
        //si je suis dans l position 1 desactiver button precedent
            $("#prev_" + idmedcin).addClass("disabled");
        else
            $("#prev_" + idmedcin).removeClass("disabled");

       

        $.ajax({
            url: '/Home/GetPartial',
            type: 'GET',
            // passer les données qui sont en param
            data: { num: pos[i], medcinid: idmedcin },
            success: function (data) {
                $("#mycontent_" + idmedcin).html(data);
            }
        });
    }
    $(document).ready(function () {
        var doctors = document.getElementsByClassName("mycontent");
        console.log("n=" + doctors.length);
        var medid = 0;
        for (let i = 0; i < doctors.length; i++) {
            medid = parseInt(doctors[i].id.replace("mycontent_", ""));
            pos.push(1);
            getcalendar(i, 0, medid);
        }
    });
</script>
<!-- MAKE AN APPOINTMENT -->
<section id="appointment" data-stellar-background-ratio="3">
    <div class="container">
        <div class="row">
            <div class="col-lg col-sm-6">
            </div>
            <div class="col-lg col-sm-6">
                <!-- CONTACT FORM HERE -->
                @{
                    int i = 0;
                }
                @foreach (var doctor in medcins)
                {
                    <div class="row">
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="card mb">
                                <div class="card-body">
                                    <h4>@doctor.Nom @doctor.Prenom</h4>
                                    <a href="/Disponibilite/Add" class="text-success">
                                        <i class="mdi mdi-calendar-plus"></i>
                                    </a>
                                    <div class="row">
                                        <div class="col-md-1">
                                            <a href="javascript:getcalendar(@i,-1,@doctor.Id);" id="prev_@doctor.Id" class="btn disabled">
                                                <i class="fa fa-chevron-left"></i>
                                            </a>
                                        </div>
                                        <div class="col-md-10">
                                        </div>
                                        <div class="col-md-1">
                                            <a href="javascript:getcalendar(@i,1,@doctor.Id);" id="next_@doctor.Id" class="btn">
                                                <i class="fa fa-chevron-right"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <div id="mycontent_@doctor.Id" class="mycontent">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    i++;
                }
            </div>
        </div>
    </div>
</section>

<script>
    //optimiser sidebar
    document.body.classList.add("sidebar-icon-only");
</script>

GstCabinetClient/Views/RendezVous/Add.cshtml
@model Patient
@{
    if (Context.Session.GetInt32("Idispo") == null || Context.Session.GetInt32("Idmed")==null)
    {
        Context.Response.Redirect("/Home/Index");
    }
}
<div class="col-md-6 col-sm-6">
    <!-- CONTACT FORM HERE -->
    <form id="appointment-form" role="form" method="post" action="#">

        <!-- SECTION TITLE -->
        <div class="section-title wow fadeInUp" data-wow-delay="0.4s">
            <h2>Prenez Rendez-Vous</h2>
        </div>

        <div class="wow fadeInUp" data-wow-delay="0.8s">
            @if (Context.Session.GetInt32("Id") == null)
            {
                <div class="col-md-6 col-sm-6">
                    <label for="name">Nom</label>
                    <input type="text" class="form-control"  asp-for="Nom" placeholder="Nom">
                    <span asp-validation-for="Nom"></span>
                </div>

                <div class="col-md-6 col-sm-6">
                    <label for="name">Prenom</label>
                    <input type="text" class="form-control"  asp-for="Prenom" placeholder="Prenom">
                    <span asp-validation-for="Prenom"></span>
                </div>

                <div class="col-md-6 col-sm-6">
                    <label for="name">Adresse</label>
                    <input type="text" class="form-control"  asp-for="Adresse" placeholder="Adresse">
                    <span asp-validation-for="Adresse"></span>
                </div>
                <div class="col-md-6 col-sm-6">
                    <label for="name">Telephone</label>
                    <input type="text" class="form-control"asp-for="Telephone" placeholder="Telephone">
                    <span asp-validation-for="Telephone"></span>
                </div>
                <div class="col-md-6 col-sm-6">
                    <label for="name">Email</label>
                    <input type="email" class="form-control"  asp-for="Email" placeholder="Email">
                    <span asp-validation-for="Email"></span>
                </div>
                <div class="col-md-6 col-sm-6">
                    <label for="name">Password</label>
                    <input type="password" class="form-control"  asp-for="Password" placeholder="Password">
                    <span asp-validation-for="Password"></span>
                </div>


                <div class="col-md-6 col-sm-6">
                    <label for="select">Sexe</label>
                    <select class="form-control" asp-for="Sexe">
                        <option>Homme</option>
                        <option>Femme</option>

                    </select>
                    <span asp-validation-for="Sexe"></span>
                </div>
                <div class="col-md-6 col-sm-6">
                    <label for="name">Date Naissance</label>
                <input type="date" class="form-control" id="name" asp-for="DateNaissance" placeholder="Date Naissance">
                <span asp-validation-for="DateNaissance"></span>
            </div>

            }
            <div class="col-md-12 col-sm-12"><br />
                
                <button type="submit" class="form-control btn btn-success" id="cf-submit" name="submit">Valider le rendez vous</button>
            </div>
        </div>
    </form>
</div>

             

GstCabinetClient/Views/RendezVous/List.cshtml
@model List<RendezVous>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th> Numero</th>
                            <th> Date RendezVous </th>
                            <th> Horraire </th>
                            <th> Nom Medcin </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (RendezVous rd in Model)
                        {
                            <tr>
                                <td> @rd.Num</td>
                                <td>@rd.Date.ToString("dd-MM-yyyy")</td>
                                <td> @rd.Horraire </td>
                                
                                <td> @rd.Medcin.Nom @rd.Medcin.Prenom</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

GstCabinetClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Tooplate">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/css/tooplate-style.css">
</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
    <!-- MENU -->
    <section class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">

            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                </button>
            </div>
            <!-- MENU LINKS -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/Home/Index" class="smoothScroll">Home</a></li>
                    <li class="appointment-btn"><a href="/Authentification/Connect">Se connecter</a></li>
                   
                </ul>
            </div>

        </div>
    </section>
  @*  @model List<Disponibilite>
    @{
        var medcins = ViewBag.doctors as List<Medcin>;
    }
    <!-- MAKE AN APPOINTMENT -->
    <section id="appointment" data-stellar-background-ratio="3">
        <div class="container">
            <div class="row">

                <div class="col-lg col-sm-6">
           </div>

                <div class="col-lg col-sm-6">
                    <!-- CONTACT FORM HERE -->
                     @foreach (var doctor in medcins)
    {
                            <div class="col-lg-11 grid-margin stretch-card">
                                <div class="card mb">
                                    <div class="card-body">
                                        <h4>@doctor.Nom @doctor.Prenom</h4>
                                        <div class="table-responsive">
                                            <table class="table" cellspacing="0">
                                                <a href="/Disponibilite/Add" class="text-success">
                                                    <i class="mdi mdi-calendar-plus
"></i>
                                                </a>
                                                <thead>
                                                    <tr>
                                                        <th>
                                                        </th>
                                                        @{
                                                            int annee = DateTime.Now.Year;
                                                            int mois = DateTime.Now.Month;
                                                            int nombreJours = DateTime.DaysInMonth(annee, mois);
                                                        }
                                                        @for (int i = DateTime.Now.Day; i <= nombreJours; i++)
                                                        {
                                                            <th>
                                                                <center>
                                                                    @DateTime.Now.AddDays(i-DateTime.Now.Day).ToString("dddd")<br />
                                                                    @DateTime.Now.AddDays(i-DateTime.Now.Day).ToString("dd-MM-yyyy")
                                                                </center>
                                                            </th>
                                                        }
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @{
                                                        var horraire = Model.Where(x=>x.MedcinID==doctor.Id).Select(h => new { h.Horraire }).Distinct().OrderBy(h => h.Horraire).ToList();
                                                    }
                                                    @foreach (var dispo in horraire)
                                                    {
                                                        <tr>
                                                            <td>
                                                                @dispo.Horraire
                                                            </td>

                                                            @for (int i = DateTime.Now.Day; i <= nombreJours; i++)
                                                            {
                                                                var disp = Model.Where(d=>d.MedcinID==doctor.Id && d.Horraire == dispo.Horraire && d.DateRendezvous.Year == DateTime.Now.AddDays(i - DateTime.Now.Day).Year && d.DateRendezvous.Month == DateTime.Now.AddDays(i - DateTime.Now.Day).Month && d.DateRendezvous.Day == DateTime.Now.AddDays(i - DateTime.Now.Day).Day).FirstOrDefault();
                                                                if (disp != null)
                                                                {
                                                                    <td>

                                                                    <a href="/RendezVous/Add/@disp.Id/@doctor.Id" class="btn btn-success">
                                                                        Disponible 
                                                                        </a>

                                                                    </td>
                                                                }
                                                                else
                                                                {
                                                                    <td>
                                                                        <span class="badge badge-danger">Non disponible</span>
                                                                    </td>
                                                                }
                                                            }

                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <script>
                                //optimiser sidebar
                                document.body.classList.add("sidebar-icon-only");
                            </script>

                            }
                        
                        </div>
                    </div>
        </div>
    </section>*@


  
    @RenderBody();

    <!-- FOOTER -->
    <footer data-stellar-background-ratio="5">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 border-top">
                    <div class="col-md-4 col-sm-6">
                        <div class="copyright-text">
                            <p>
                                Copyright &copy; 2023 Your Company

                                
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="footer-link">
                            <a href="#">Laboratory Tests</a>
                            <a href="#">Departments</a>
                            <a href="#">Insurance Policy</a>
                            <a href="#">Careers</a>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-2 text-align-center">
                        <div class="angle-up-btn">
                            <a href="#top" class="smoothScroll wow fadeInUp" data-wow-delay="1.2s"><i class="fa fa-angle-up"></i></a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </footer>

    <!-- SCRIPTS -->
    <!-- SCRIPTS -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/smoothscroll.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/custom.js"></script>

</body>
</html>